### ISSUE TITLE
Autoreload for development

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#184] opened 2016-08-22 11:40 UTC
During development, especially when styling, an auto-reload feature for at least the webruntimes would be a nice boost for productivity.

Tornado offers this: http://www.tornadoweb.org/en/stable/autoreload.html
Alternatively you can use watchdog to implement something similar: https://pypi.python.org/pypi/watchdog

**Comment by almarklein** [comment] 2016-08-29 22:38
Duplicate of #8

**Closed by almarklein** 2016-08-29 22:38 UTC
Labels: reso: duplicate
