### ISSUE TITLE
Provide an efficient way to transfer images to JS

### ISSUE THREAD

**Issue by eudoxos** [zoofIO/flexx#211] opened 2016-09-14 11:16 UTC
I am using flexx to display image acquisition data (1600x1200 bw images) occasionally read from camera. I currently convert the numpy array to flat list, pass it throught the event, and on the JS side construct Uint8ClampedArray from the list, create ImageData and finally use getContext('2d').putImageData to show it on the canvas. It is painfully slow (15s for the whole process). I will experiment with other options (such as creating img with inline bease64-encoded data), but I suspect this could be quite useful for other people as well. (Thank you for flexx, I am really enjoing it!)

**Comment by Korijn** [comment] 2016-09-14 11:33
Related to #143

**Comment by almarklein** [comment] 2016-09-14 12:40
I'm pretty sure this is a duplicate of #143 even :)

**Closed** 2016-09-14 12:40 UTC
Labels: reso: duplicate

**Comment by almarklein** [comment] 2016-09-14 12:41
@eudoxos it's likely that this will be worked on somewhere in the next few months

**Comment by eudoxos** [comment] 2016-09-14 12:55
For the record, I found it is quite efficient to encode the PNG as base64, pass it (utf-8 encoded) as event attribute, then set `ImageWidget.source` to `image/png;base64,...`.

**Comment by almarklein** [comment] 2016-09-14 14:13
Yes, that's at least better than serializing it as list, but still suffers from base64 encoding, plus that the websocket is unavailable for flexx stuff while the data is being transferred. My bet is on ajax.

**Comment by eudoxos** [comment] 2016-09-15 05:16
Another option is to create an asset on the fly (give it maybe md5 digest URL) and pass that URL to the client. The downside is that it will stay on the server forever. Did not try, just an idea.

**Comment by almarklein** [comment] 2016-09-15 09:27
That is part of the Ajax idea. With png images etc. you can make the browser load these assets automatically. With arbitrary data you need to make the client fetch the data via `XMLHttpRequest()`, a.k.a. Ajax.
