### ISSUE TITLE
Dynamically add/remove widgets

### ISSUE THREAD

**Issue by frmdstryr** [zoofIO/flexx#363] opened 2017-02-22 19:50 UTC
Is it possible to add & remove widgets dynamically? 

For instance adding or removing a row to a table.

**Comment by almarklein** [comment] 2017-02-24 12:25
Yes, you can set the parent of q widget to `None` (or simply remove it from the parent's list of children. This more or less a duplicate of #182

**Closed by almarklein** 2017-02-24 12:25 UTC
